### ISSUE TITLE
Firmware 24.7.4.1 installation fails when encryption enabled

### ISSUE THREAD

**Issue by iamwillbar** [ApolloAutomation/AIR-1#27]
I had enabled encryption in the ESP Home config for my AIR-1, which hasn't been an issue, but when installing the 24.7.4.1 firmware through Home Assistant the AIR-1 becomes unresponsive and the ESP Home log shows:
```
INFO Successfully connected to apollo-air-1-[REDACTED] @ [REDACTED] in 0.031s
WARNING apollo-air-1-[REDACTED] @ [REDACTED]: Connection error occurred: apollo-air-1-[REDACTED] @ [REDACTED]: The connection dropped immediately after encrypted hello; Try enabling encryption on the device or turning off encryption on the client (ESPHome Logs 2024.6.6).
```

My config is:
```
substitutions:
  name: apollo-air-1-[REDACTED]
  friendly_name: Kitchen AIR-1
packages:
  ApolloAutomation.AIR-1: github://ApolloAutomation/AIR-1/Integrations/ESPHome/AIR-1.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: [REDACTED]
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

The AIR-1 can be brought back online by running install from ESP Home again, but when it comes back online it immediately shows that there is an updated firmware available.
